/**
 * Task Completion Hooks Service
 *
 * Handles automatic actions when Kanban tasks are moved to "done" column:
 * 1. Generate AI summary of task conversation
 * 2. Save to MCP Memory (Second Brain)
 * 3. Create documentation in /docs folder
 * 4. Notify user of completion
 *
 * Executes asynchronously in the background - non-blocking for user.
 *
 * @module services/taskCompletionHooks
 */

import { invoke } from "@tauri-apps/api/core";
import { toast } from "sonner";
import {
  createMCPEntity,
  createMCPRelation,
  ensureProjectEntity,
  generateEntityName,
  PROJECT_RELATION_TYPE,
} from "./mcpMemoryService";
import type { KanbanTask, ChatMessage } from "../types";

/**
 * Context for task completion processing
 */
export interface TaskCompletionContext {
  /** Completed Kanban task */
  task: KanbanTask;
  /** All chat messages associated with the task */
  chatMessages: ChatMessage[];
  /** Optional configuration for completion processing */
  options?: {
    /** Skip documentation file creation */
    skipDocumentation?: boolean;
    /** Source of completion (for tracking) */
    source?: "user" | "agent" | "automation";
  };
}

/**
 * Result of task completion processing
 */
export interface CompletionResult {
  /** Success status */
  success: boolean;
  /** MCP Memory entity ID (if created) */
  memoryEntityId?: string;
  /** Path to created documentation file (if created) */
  docFilePath?: string;
  /** AI-generated summary of task */
  summary?: string;
  /** Whether documentation was skipped */
  skipped?: boolean;
  /** Error message if failed */
  error?: string;
}

/**
 * Summary generated by AI for completed task
 */
interface TaskSummary {
  /** Short title (1-5 words) */
  title: string;
  /** Detailed summary (2-3 sentences) */
  summary: string;
  /** Key accomplishments (bullet points) */
  accomplishments: string[];
  /** Lessons learned or important notes */
  lessons?: string[];
  /** Technical details or gotchas */
  technicalNotes?: string[];
}

/**
 * Format date as YYYY-MM-DD
 */
function formatDateForFile(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

/**
 * Sanitize text for use in filename
 * Removes special characters and limits length
 */
function sanitizeForFilename(text: string, maxLength: number = 50): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, maxLength);
}

/**
 * Generate AI summary of task conversation
 * Analyzes chat messages to extract key information
 *
 * @param task - Completed Kanban task
 * @param messages - Chat messages from the task
 * @returns AI-generated summary or null on failure
 */
async function generateTaskSummary(
  task: KanbanTask,
  messages: ChatMessage[]
): Promise<TaskSummary | null> {
  try {
    // Filter out system messages and focus on user/assistant dialogue
    const relevantMessages = messages.filter(
      (m) => m.role === "user" || m.role === "assistant"
    );

    if (relevantMessages.length === 0) {
      // No conversation - use task details
      return {
        title: task.title,
        summary: task.prompt || task.title,
        accomplishments: ["Task completed successfully"],
      };
    }

    // Build conversation text for analysis
    const conversationText = relevantMessages
      .map((m) => {
        const role = m.role === "user" ? "User" : "Assistant";
        return `${role}: ${m.content.slice(0, 500)}`; // Limit to 500 chars per message
      })
      .join("\n\n");

    // Call Tauri backend to generate summary using Claude
    const summary = await invoke<TaskSummary>("generate_task_summary", {
      taskTitle: task.title,
      taskPrompt: task.prompt,
      conversationText,
      projectName: task.projectName,
    });

    console.log("[TaskCompletionHooks] Summary generated:", summary.title);
    return summary;
  } catch (error) {
    console.error("[TaskCompletionHooks] Failed to generate summary:", error);
    // Return basic fallback summary
    return {
      title: task.title,
      summary: task.prompt || task.title,
      accomplishments: ["Task completed"],
    };
  }
}

/**
 * Save task completion to MCP Memory (Second Brain)
 * Creates entity with task details and links to project
 *
 * @param task - Completed Kanban task
 * @param summary - AI-generated summary
 * @returns Entity ID or null on failure
 */
async function saveToMemory(
  task: KanbanTask,
  summary: TaskSummary
): Promise<string | null> {
  try {
    // Ensure project entity exists
    const projectExists = await ensureProjectEntity(
      task.projectName,
      task.projectPath
    );

    if (!projectExists) {
      console.warn(
        "[TaskCompletionHooks] Failed to ensure project entity:",
        task.projectName
      );
      // Continue anyway - entity will be created without project scope
    }

    // Get current date for observation prefix
    const today = formatDateForFile(new Date());

    // Build observations array
    const observations: string[] = [
      `[${today}] Task: ${summary.title}`,
      `Summary: ${summary.summary}`,
    ];

    // Add accomplishments
    if (summary.accomplishments && summary.accomplishments.length > 0) {
      observations.push(
        `Accomplishments: ${summary.accomplishments.join("; ")}`
      );
    }

    // Add lessons learned
    if (summary.lessons && summary.lessons.length > 0) {
      observations.push(`Lessons: ${summary.lessons.join("; ")}`);
    }

    // Add technical notes
    if (summary.technicalNotes && summary.technicalNotes.length > 0) {
      observations.push(`Technical: ${summary.technicalNotes.join("; ")}`);
    }

    // Add task metadata
    if (task.assignedAgent) {
      observations.push(`Agent: ${task.assignedAgent.name}`);
    }
    if (task.branch) {
      observations.push(`Branch: ${task.branch}`);
    }
    if (task.totalCost) {
      observations.push(`Cost: $${task.totalCost.toFixed(4)}`);
    }

    // Generate unique entity name
    const entityName = generateEntityName(summary.title);

    // Create entity in MCP Memory
    const entity = await createMCPEntity({
      name: entityName,
      entityType: "pattern", // Use 'pattern' type for completed tasks
      observations,
    });

    if (!entity) {
      return null;
    }

    // Link to project if entity exists
    if (projectExists) {
      await createMCPRelation({
        from: entityName,
        to: task.projectName,
        relationType: PROJECT_RELATION_TYPE,
      });
    }

    console.log("[TaskCompletionHooks] Saved to memory:", entityName);
    return entityName;
  } catch (error) {
    console.error("[TaskCompletionHooks] Failed to save to memory:", error);
    return null;
  }
}

/**
 * Create documentation file in project's /docs folder
 * Generates markdown file with task details, summary, and conversation
 *
 * @param task - Completed Kanban task
 * @param summary - AI-generated summary
 * @param messages - Chat messages from the task
 * @returns Path to created file or null on failure
 */
async function createDocumentation(
  task: KanbanTask,
  summary: TaskSummary,
  messages: ChatMessage[]
): Promise<string | null> {
  try {
    const today = formatDateForFile(new Date());
    const titleSlug = sanitizeForFilename(summary.title);
    const filename = `${today}-${titleSlug}.md`;

    // Build docs directory path
    const docsDir = `${task.projectPath}/docs/kanban-completed`;
    const filePath = `${docsDir}/${filename}`;

    // Build markdown content
    const markdownContent = buildMarkdownDocument(task, summary, messages);

    // Write file using Tauri filesystem
    await invoke("write_file", {
      path: filePath,
      contents: markdownContent,
    });

    console.log("[TaskCompletionHooks] Documentation created:", filePath);
    return filePath;
  } catch (error) {
    console.error(
      "[TaskCompletionHooks] Failed to create documentation:",
      error
    );
    return null;
  }
}

/**
 * Build markdown document for task completion
 */
function buildMarkdownDocument(
  task: KanbanTask,
  summary: TaskSummary,
  messages: ChatMessage[]
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${summary.title}`);
  lines.push("");
  lines.push(`**Completed:** ${new Date().toISOString()}`);
  lines.push(`**Project:** ${task.projectName}`);
  if (task.assignedAgent) {
    lines.push(`**Agent:** ${task.assignedAgent.name}`);
  }
  if (task.branch) {
    lines.push(`**Branch:** ${task.branch}`);
  }
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(summary.summary);
  lines.push("");

  // Accomplishments
  if (summary.accomplishments && summary.accomplishments.length > 0) {
    lines.push("## Accomplishments");
    lines.push("");
    summary.accomplishments.forEach((item) => {
      lines.push(`- ${item}`);
    });
    lines.push("");
  }

  // Lessons Learned
  if (summary.lessons && summary.lessons.length > 0) {
    lines.push("## Lessons Learned");
    lines.push("");
    summary.lessons.forEach((item) => {
      lines.push(`- ${item}`);
    });
    lines.push("");
  }

  // Technical Notes
  if (summary.technicalNotes && summary.technicalNotes.length > 0) {
    lines.push("## Technical Notes");
    lines.push("");
    summary.technicalNotes.forEach((item) => {
      lines.push(`- ${item}`);
    });
    lines.push("");
  }

  // Task Details
  lines.push("## Task Details");
  lines.push("");
  lines.push("**Original Prompt:**");
  lines.push("");
  lines.push(task.prompt || task.title);
  lines.push("");

  // Token Usage (if available)
  if (task.inputTokens || task.outputTokens || task.totalCost) {
    lines.push("**Token Usage:**");
    lines.push("");
    if (task.inputTokens) {
      lines.push(`- Input tokens: ${task.inputTokens.toLocaleString()}`);
    }
    if (task.outputTokens) {
      lines.push(`- Output tokens: ${task.outputTokens.toLocaleString()}`);
    }
    if (task.totalCost) {
      lines.push(`- Total cost: $${task.totalCost.toFixed(4)}`);
    }
    lines.push("");
  }

  // Conversation (last 5 messages)
  if (messages.length > 0) {
    lines.push("## Conversation Highlights");
    lines.push("");
    const highlights = messages.slice(-5); // Last 5 messages
    highlights.forEach((msg) => {
      const role = msg.role === "user" ? "User" : "Assistant";
      lines.push(`### ${role}`);
      lines.push("");
      // Truncate long messages
      const content =
        msg.content.length > 1000
          ? msg.content.slice(0, 1000) + "..."
          : msg.content;
      lines.push(content);
      lines.push("");
    });
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(
    "_This document was auto-generated by Quack's task completion hooks._"
  );

  return lines.join("\n");
}

/**
 * Main hook: Process task completion
 * Called when a Kanban task is moved to "done" column
 *
 * Executes asynchronously and non-blocking:
 * 1. Generate AI summary
 * 2. Save to MCP Memory
 * 3. Create documentation file
 * 4. Notify user
 *
 * @param ctx - Task completion context
 * @returns Completion result
 */
export async function onTaskComplete(
  ctx: TaskCompletionContext
): Promise<CompletionResult> {
  const { task, chatMessages, options } = ctx;

  console.log("[TaskCompletionHooks] Processing task completion:", task.title);

  try {
    // Step 1: Generate AI summary
    toast.info("Generating task summary...");
    const summary = await generateTaskSummary(task, chatMessages);

    if (!summary) {
      return {
        success: false,
        error: "Failed to generate task summary",
      };
    }

    // Step 2: Save to MCP Memory
    toast.info("Saving to Second Brain...");
    const memoryEntityId = await saveToMemory(task, summary);

    // Step 3: Create documentation (if not skipped)
    let docFilePath: string | null = null;
    if (!options?.skipDocumentation) {
      toast.info("Creating documentation...");
      docFilePath = await createDocumentation(task, summary, chatMessages);
    }

    // Step 4: Notify user
    if (memoryEntityId && docFilePath) {
      toast.success("Task completion processed successfully", {
        description: `Memory saved & docs created`,
      });
    } else if (memoryEntityId) {
      toast.success("Task saved to Second Brain", {
        description: "Documentation skipped",
      });
    } else {
      toast.warning("Task completed with partial processing", {
        description: "Some steps failed",
      });
    }

    return {
      success: true,
      memoryEntityId: memoryEntityId || undefined,
      docFilePath: docFilePath || undefined,
      summary: summary.summary,
      skipped: options?.skipDocumentation === true,
    };
  } catch (error) {
    console.error("[TaskCompletionHooks] Task completion failed:", error);
    toast.error("Failed to process task completion", {
      description: error instanceof Error ? error.message : "Unknown error",
    });

    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

/**
 * Batch process multiple completed tasks
 * Useful for retroactive processing or bulk operations
 *
 * @param contexts - Array of task completion contexts
 * @returns Array of completion results
 */
export async function batchProcessCompletions(
  contexts: TaskCompletionContext[]
): Promise<CompletionResult[]> {
  console.log(
    "[TaskCompletionHooks] Batch processing",
    contexts.length,
    "tasks"
  );

  const results: CompletionResult[] = [];

  for (const ctx of contexts) {
    const result = await onTaskComplete(ctx);
    results.push(result);

    // Small delay between tasks to avoid overwhelming the system
    await new Promise((resolve) => setTimeout(resolve, 500));
  }

  const successCount = results.filter((r) => r.success).length;
  toast.success(`Processed ${successCount}/${contexts.length} tasks`);

  return results;
}

/**
 * Check if task completion hooks are enabled
 * Reads from settings or environment
 *
 * @returns true if hooks are enabled
 */
export async function areHooksEnabled(): Promise<boolean> {
  try {
    // For now, always return true
    // In the future, add settings UI to toggle this
    return true;
  } catch (error) {
    console.error("[TaskCompletionHooks] Failed to check hook status:", error);
    return false;
  }
}

/**
 * Preview what will be saved without actually saving
 * Useful for testing or showing user before confirming
 *
 * @param ctx - Task completion context
 * @returns Preview of what will be created
 */
export async function previewCompletion(ctx: TaskCompletionContext): Promise<{
  summary: TaskSummary | null;
  memoryObservations: string[];
  documentContent: string;
}> {
  const { task, chatMessages } = ctx;

  // Generate summary
  const summary = await generateTaskSummary(task, chatMessages);

  if (!summary) {
    return {
      summary: null,
      memoryObservations: [],
      documentContent: "",
    };
  }

  // Build memory observations
  const today = formatDateForFile(new Date());
  const memoryObservations: string[] = [
    `[${today}] Task: ${summary.title}`,
    `Summary: ${summary.summary}`,
  ];

  if (summary.accomplishments && summary.accomplishments.length > 0) {
    memoryObservations.push(
      `Accomplishments: ${summary.accomplishments.join("; ")}`
    );
  }

  // Build document content
  const documentContent = buildMarkdownDocument(task, summary, chatMessages);

  return {
    summary,
    memoryObservations,
    documentContent,
  };
}
