// Markdown formatter for AI consumption
console.log('🦆 Quack Markdown Formatter loaded');

class MarkdownFormatter {
  // Format component info as markdown for AI
  static format(componentInfo) {
    if (!componentInfo) return '## No component detected';

    const lines = [];

    // Header
    lines.push(`## 🦆 Component Inspector`);
    lines.push('');

    // Framework
    lines.push(`**Framework**: ${componentInfo.framework}`);
    lines.push('');

    // Component-specific formatting
    switch (componentInfo.framework) {
      case 'React':
        this.formatReactComponent(lines, componentInfo);
        break;
      case 'Vue':
        this.formatVueComponent(lines, componentInfo);
        break;
      case 'Angular':
        this.formatAngularComponent(lines, componentInfo);
        break;
      default:
        this.formatGenericElement(lines, componentInfo);
    }

    // DOM Path (always include)
    lines.push('');
    lines.push(`**DOM Path**:`);
    lines.push('```css');
    lines.push(componentInfo.domPath || 'Unknown');
    lines.push('```');

    // Footer
    lines.push('');
    lines.push('---');
    lines.push('*Generated by Quack Inspector 🦆*');

    return lines.join('\n');
  }

  // Format React component
  static formatReactComponent(lines, info) {
    // Component name
    lines.push(`**Component**: \`${info.componentName}\``);
    lines.push('');

    // Source file
    if (info.file && info.file !== 'Unknown') {
      lines.push(`**File**: \`${info.file}\``);
      lines.push('');
    }

    // Parent chain
    if (info.parentChain && info.parentChain.length > 0) {
      lines.push(`**Parent Chain**: ${info.parentChain.join(' > ')}`);
      lines.push('');
    }

    // Props
    if (info.props && Object.keys(info.props).length > 0) {
      lines.push(`**Props**:`);
      lines.push('```json');
      lines.push(JSON.stringify(this.sanitizeProps(info.props), null, 2));
      lines.push('```');
      lines.push('');
    }

    // State
    if (info.state && typeof info.state === 'object' && Object.keys(info.state).length > 0) {
      lines.push(`**State**:`);
      lines.push('```json');
      lines.push(JSON.stringify(this.sanitizeProps(info.state), null, 2));
      lines.push('```');
      lines.push('');
    }

    // Hooks
    if (info.hooks && info.hooks.length > 0) {
      lines.push(`**Hooks**: ${info.hooks.length} hook(s) detected`);
      lines.push('');
    }
  }

  // Format Vue component
  static formatVueComponent(lines, info) {
    // Component name
    lines.push(`**Component**: \`${info.componentName}\``);
    lines.push('');

    // Source file
    if (info.file && info.file !== 'Unknown') {
      lines.push(`**File**: \`${info.file}\``);
      lines.push('');
    }

    // Parent chain
    if (info.parentChain && info.parentChain.length > 0) {
      lines.push(`**Parent Chain**: ${info.parentChain.join(' > ')}`);
      lines.push('');
    }

    // Props
    if (info.props && Object.keys(info.props).length > 0) {
      lines.push(`**Props**:`);
      lines.push('```json');
      lines.push(JSON.stringify(this.sanitizeProps(info.props), null, 2));
      lines.push('```');
      lines.push('');
    }

    // Data
    if (info.data && Object.keys(info.data).length > 0) {
      lines.push(`**Data**:`);
      lines.push('```json');
      lines.push(JSON.stringify(this.sanitizeProps(info.data), null, 2));
      lines.push('```');
      lines.push('');
    }

    // Computed
    if (info.computed && Object.keys(info.computed).length > 0) {
      lines.push(`**Computed**: ${Object.keys(info.computed).join(', ')}`);
      lines.push('');
    }
  }

  // Format Angular component
  static formatAngularComponent(lines, info) {
    // Component name
    lines.push(`**Component**: \`${info.componentName}\``);
    lines.push('');

    // Properties
    if (info.properties && Object.keys(info.properties).length > 0) {
      lines.push(`**Properties**:`);
      lines.push('```json');
      lines.push(JSON.stringify(this.sanitizeProps(info.properties), null, 2));
      lines.push('```');
      lines.push('');
    }
  }

  // Format generic element
  static formatGenericElement(lines, info) {
    // Element info
    lines.push(`**Element**: \`<${info.tagName}>\``);
    lines.push('');

    if (info.id) {
      lines.push(`**ID**: \`${info.id}\``);
      lines.push('');
    }

    if (info.className) {
      lines.push(`**Classes**: \`${info.className}\``);
      lines.push('');
    }

    // Attributes
    if (info.attributes && Object.keys(info.attributes).length > 0) {
      const relevantAttrs = Object.entries(info.attributes)
        .filter(([key]) => !key.startsWith('data-react') && !key.startsWith('__'))
        .reduce((acc, [key, value]) => ({ ...acc, [key]: value }), {});

      if (Object.keys(relevantAttrs).length > 0) {
        lines.push(`**Attributes**:`);
        lines.push('```json');
        lines.push(JSON.stringify(relevantAttrs, null, 2));
        lines.push('```');
        lines.push('');
      }
    }

    // Computed styles
    if (info.computedStyles) {
      lines.push(`**Computed Styles**:`);
      lines.push('```json');
      lines.push(JSON.stringify(info.computedStyles, null, 2));
      lines.push('```');
      lines.push('');
    }
  }

  // Sanitize props (remove functions, circular refs, etc.)
  static sanitizeProps(obj, depth = 0, maxDepth = 3) {
    if (depth > maxDepth) return '[Max depth reached]';
    if (obj === null || obj === undefined) return obj;

    if (typeof obj === 'function') {
      return `[Function: ${obj.name || 'anonymous'}]`;
    }

    if (obj instanceof HTMLElement) {
      return `[HTMLElement: ${obj.tagName}]`;
    }

    if (obj instanceof Node) {
      return '[DOM Node]';
    }

    if (Array.isArray(obj)) {
      if (obj.length > 10) {
        return `[Array(${obj.length})]`;
      }
      return obj.map(item => this.sanitizeProps(item, depth + 1, maxDepth));
    }

    if (typeof obj === 'object') {
      const sanitized = {};
      const keys = Object.keys(obj);

      // Limit number of keys
      const keysToInclude = keys.slice(0, 20);

      for (let key of keysToInclude) {
        // Skip internal React/Vue keys
        if (key.startsWith('_') || key.startsWith('__')) continue;

        try {
          sanitized[key] = this.sanitizeProps(obj[key], depth + 1, maxDepth);
        } catch (error) {
          sanitized[key] = '[Error reading property]';
        }
      }

      if (keys.length > keysToInclude.length) {
        sanitized['...'] = `[${keys.length - keysToInclude.length} more properties]`;
      }

      return sanitized;
    }

    return obj;
  }

  // Format as compact single-line summary
  static formatCompact(componentInfo) {
    if (!componentInfo) return 'No component';

    switch (componentInfo.framework) {
      case 'React':
        return `${componentInfo.componentName} (${componentInfo.file || 'Unknown'})`;
      case 'Vue':
        return `${componentInfo.componentName} (${componentInfo.file || 'Unknown'})`;
      case 'Angular':
        return `${componentInfo.componentName}`;
      default:
        return `<${componentInfo.tagName}>${componentInfo.id ? `#${componentInfo.id}` : ''}`;
    }
  }
}

// Export for use in content script
if (typeof module !== 'undefined' && module.exports) {
  module.exports = MarkdownFormatter;
}
