/**
 * Monaco Editor loader configuration
 *
 * Configures @monaco-editor/react to use workers bundled by vite-plugin-monaco-editor.
 * This file must be imported before any Monaco Editor component mounts.
 */

import { loader } from '@monaco-editor/react';

/**
 * Configure Monaco loader to use local bundled workers instead of CDN.
 *
 * The workers are generated by vite-plugin-monaco-editor at build time
 * and placed in the /monacoeditorwork/ directory.
 */
loader.config({
  // Use local Monaco instance (bundled by Vite)
  // Workers are handled by vite-plugin-monaco-editor's injected MonacoEnvironment
  paths: {
    vs: 'monaco-editor/min/vs',
  },

  // Don't use CDN - we have bundled workers
  'vs/nls': {
    availableLanguages: {
      '*': 'en',
    },
  },
});

// Export for reference
export default loader;
