#!/usr/bin/env python3
"""Build documentation/workstreams/INDEX.md from per-file YAML frontmatter,
and refresh the auto-managed Current Focus block in CLAUDE.md.

Single source of truth = the YAML frontmatter on each
documentation/workstreams/NN-*.md file. Run after editing frontmatter.

Modes:
  (default)   Regenerate INDEX.md and the CLAUDE.md marker block in place.
  --check     Lint-only: parse every workstream, exit non-zero if any file
              has missing/invalid frontmatter or stale derived state.
              Does not write.

Schema (every workstream file must start with):

    ---
    ws: 19
    title: "Short topic"
    status: "Free-form status caps line"
    focus: current        # current | active | background | candidate | superseded | completed
    opened: 2026-04-27
    updated: 2026-05-13
    warning: |            # optional, multi-line
      Free-text blocker if it gates the next action.
    feature: documentation/features/...md   # optional
    absorbs: [8]                            # optional, list of WS numbers
    ---

The script is intentionally dependency-free (no pyyaml) so it works in
any project's Python environment without `pip install`.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# Resolve project root = script's parent's parent (scripts/ → project root).
REPO_ROOT = Path(__file__).resolve().parent.parent
WORKSTREAMS_DIR = REPO_ROOT / "documentation" / "workstreams"
INDEX_FILE = WORKSTREAMS_DIR / "INDEX.md"
CLAUDE_MD = REPO_ROOT / "CLAUDE.md"

ALLOWED_FOCUS = ["current", "active", "background", "candidate", "superseded", "completed"]

# Section headings in INDEX.md. Localize as needed for non-English projects.
FOCUS_HEADINGS = {
    "current": "Current focus",
    "active": "Active",
    "background": "Background / Live",
    "candidate": "Candidates (not yet scoped)",
    "superseded": "Superseded",
    "completed": "Completed",
}

MARKER_START = "<!-- WS-CURRENT-START — auto-generated by scripts/build-workstream-index.py. Do not hand-edit. -->"
MARKER_END = "<!-- WS-CURRENT-END -->"


@dataclass
class Workstream:
    ws: int
    title: str
    status: str
    focus: str
    opened: str | None = None
    updated: str | None = None
    warning: str | None = None
    feature: str | None = None
    absorbs: list[int] = field(default_factory=list)
    brand: str | None = None
    brands: list[str] = field(default_factory=list)
    file: Path = Path()


def parse_frontmatter(text: str, path: Path) -> dict:
    """Tiny YAML-subset parser for our fixed schema. Supports:
       key: unquoted string
       key: "quoted string"
       key: 42
       key: [1, 2, 3]
       key: |    (followed by indented multi-line block)
    """
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: missing frontmatter (file must start with '---')")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise ValueError(f"{path}: frontmatter not terminated by '---'")
    block = text[4:end]
    out: dict = {}
    lines = block.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*):\s*(.*)$", line)
        if not m:
            raise ValueError(f"{path}: cannot parse frontmatter line: {line!r}")
        key, raw = m.group(1), m.group(2).rstrip()
        if not (raw.startswith('"') or raw.startswith("'")):
            raw = re.sub(r"\s+#.*$", "", raw).rstrip()
        if raw == "|":
            block_lines = []
            i += 1
            while i < len(lines) and (lines[i].startswith("  ") or lines[i].strip() == ""):
                block_lines.append(lines[i][2:] if lines[i].startswith("  ") else lines[i])
                i += 1
            out[key] = "\n".join(block_lines).rstrip()
            continue
        if raw.startswith("[") and raw.endswith("]"):
            inner = raw[1:-1].strip()
            items = [x.strip() for x in inner.split(",") if x.strip()]
            out[key] = [int(x) if x.isdigit() else x.strip('"\'') for x in items]
        elif raw.startswith('"') and raw.endswith('"'):
            out[key] = raw[1:-1]
        elif raw.startswith("'") and raw.endswith("'"):
            out[key] = raw[1:-1]
        elif raw.isdigit() or (raw.startswith("-") and raw[1:].isdigit()):
            out[key] = int(raw)
        else:
            out[key] = raw
        i += 1
    return out


def load_workstreams() -> list[Workstream]:
    items: list[Workstream] = []
    errors: list[str] = []
    for path in sorted(WORKSTREAMS_DIR.glob("*.md")):
        if path.name == "INDEX.md":
            continue
        text = path.read_text(encoding="utf-8")
        try:
            fm = parse_frontmatter(text, path)
        except ValueError as e:
            errors.append(str(e))
            continue
        missing = [k for k in ("ws", "title", "status", "focus") if k not in fm]
        if missing:
            errors.append(f"{path}: missing required field(s): {', '.join(missing)}")
            continue
        if fm["focus"] not in ALLOWED_FOCUS:
            errors.append(
                f"{path}: unknown focus value {fm['focus']!r} "
                f"(allowed: {', '.join(ALLOWED_FOCUS)})"
            )
            continue
        items.append(
            Workstream(
                ws=int(fm["ws"]),
                title=str(fm["title"]),
                status=str(fm["status"]),
                focus=str(fm["focus"]),
                opened=fm.get("opened"),
                updated=fm.get("updated"),
                warning=fm.get("warning"),
                feature=fm.get("feature"),
                absorbs=fm.get("absorbs", []),
                brand=fm.get("brand"),
                brands=fm.get("brands", []),
                file=path,
            )
        )
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(2)
    return items


def md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ").strip()


def build_index_markdown(items: list[Workstream]) -> str:
    items_sorted = sorted(items, key=lambda x: x.ws)
    lines: list[str] = []
    lines.append("# Workstream Index")
    lines.append("")
    lines.append("> Auto-generated by `scripts/build-workstream-index.py`. Do not hand-edit.")
    lines.append("> Source of truth: YAML frontmatter on each `NN-*.md` file in this directory.")
    lines.append("")
    lines.append(f"Total workstreams: **{len(items_sorted)}**.")
    lines.append("")

    for focus in ALLOWED_FOCUS:
        bucket = [w for w in items_sorted if w.focus == focus]
        if not bucket:
            continue
        lines.append(f"## {FOCUS_HEADINGS[focus]}")
        lines.append("")
        lines.append("| # | Title | Status | Notes |")
        lines.append("|---|---|---|---|")
        for w in bucket:
            notes_parts = []
            if w.warning:
                notes_parts.append("⚠️ " + md_escape(w.warning))
            if w.absorbs:
                notes_parts.append("absorbs WS" + ", WS".join(str(a) for a in w.absorbs))
            if w.updated:
                notes_parts.append(f"upd {w.updated}")
            notes = " · ".join(notes_parts) if notes_parts else ""
            doc_link = f"[`{w.file.name}`](./{w.file.name})"
            lines.append(
                f"| {w.ws} | **{md_escape(w.title)}** ({doc_link}) "
                f"| {md_escape(w.status)} | {notes} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def build_current_focus_block(items: list[Workstream]) -> str:
    current = sorted([w for w in items if w.focus == "current"], key=lambda x: x.ws)
    lines = [MARKER_START]
    if not current:
        lines.append("- *(no workstreams currently marked `focus: current` — see `documentation/workstreams/INDEX.md`)*")
    else:
        for w in current:
            extra = f" — ⚠️ {w.warning.splitlines()[0]}" if w.warning else ""
            lines.append(f"- **WS{w.ws}** — {w.title} — {w.status}{extra}")
    lines.append(MARKER_END)
    return "\n".join(lines)


def update_claude_md(block: str) -> bool:
    """Replace content between markers in CLAUDE.md. Returns True if changed."""
    if not CLAUDE_MD.exists():
        print(f"WARN: {CLAUDE_MD} not found — skipping Current Focus block update", file=sys.stderr)
        return False
    text = CLAUDE_MD.read_text(encoding="utf-8")
    start_re = re.compile(r"<!-- WS-CURRENT-START\b[^>]*-->")
    end_re = re.compile(r"<!-- WS-CURRENT-END\b[^>]*-->")
    start_match = start_re.search(text)
    end_match = end_re.search(text)
    if not start_match or not end_match:
        print(
            "ERROR: CLAUDE.md is missing the WS-CURRENT-START / WS-CURRENT-END markers. "
            "Add them by hand once (see project-ops skill: templates/claude-md-snippets.md); "
            "this script only refreshes between them.",
            file=sys.stderr,
        )
        sys.exit(3)
    if end_match.start() < start_match.end():
        print("ERROR: WS-CURRENT-END appears before WS-CURRENT-START in CLAUDE.md.", file=sys.stderr)
        sys.exit(3)
    new_text = text[: start_match.start()] + block + text[end_match.end():]
    if new_text == text:
        return False
    CLAUDE_MD.write_text(new_text, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Lint-only: validate frontmatter and confirm INDEX.md + CLAUDE.md are up to date. Exits non-zero if regeneration is needed.",
    )
    args = parser.parse_args()

    if not WORKSTREAMS_DIR.is_dir():
        print(f"ERROR: {WORKSTREAMS_DIR} not found", file=sys.stderr)
        return 1

    items = load_workstreams()
    index_md = build_index_markdown(items)
    block = build_current_focus_block(items)

    if args.check:
        problems: list[str] = []
        if INDEX_FILE.exists():
            current = INDEX_FILE.read_text(encoding="utf-8")
            if current != index_md:
                problems.append(f"{INDEX_FILE.relative_to(REPO_ROOT)} is out of date")
        else:
            problems.append(f"{INDEX_FILE.relative_to(REPO_ROOT)} does not exist")
        if CLAUDE_MD.exists():
            text = CLAUDE_MD.read_text(encoding="utf-8")
            start = re.search(r"<!-- WS-CURRENT-START\b[^>]*-->", text)
            end = re.search(r"<!-- WS-CURRENT-END\b[^>]*-->", text)
            if start and end and end.start() > start.end():
                in_place = text[start.start():end.end()]
                if in_place != block:
                    problems.append("CLAUDE.md Current Focus block is out of date")
        if problems:
            for p in problems:
                print(f"CHECK FAILED: {p}", file=sys.stderr)
            print("Run `python3 scripts/build-workstream-index.py` to regenerate.", file=sys.stderr)
            return 4
        print("OK: all workstreams valid, INDEX.md and CLAUDE.md up to date.")
        return 0

    prev_index = INDEX_FILE.read_text(encoding="utf-8") if INDEX_FILE.exists() else None
    if prev_index != index_md:
        INDEX_FILE.write_text(index_md, encoding="utf-8")
        print(f"wrote {INDEX_FILE.relative_to(REPO_ROOT)} ({len(items)} workstreams)")
    else:
        print(f"{INDEX_FILE.relative_to(REPO_ROOT)} unchanged")

    if update_claude_md(block):
        print(f"updated Current Focus block in {CLAUDE_MD.relative_to(REPO_ROOT)}")
    else:
        if CLAUDE_MD.exists():
            print(f"{CLAUDE_MD.relative_to(REPO_ROOT)} Current Focus block unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
