import type { ChatMessage } from "./ai";
import type { ProviderId } from "./providers/types";
import type { ChatComposerDraft } from "./composerDraft";
import {
  deleteSessionOnDisk,
  flushSessionToDisk,
  getCachedSession,
  getCachedSessions,
  getCachedSessionIds,
  legacySaveToLocalStorage,
  putCachedSession,
  removeCachedSession,
} from "./chatStoreCache";
import { remove } from "./localStore";

export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  model?: string;
  updatedAt: number;
  providerSessionIds?: Partial<Record<ProviderId, string>>;
  claudeSessionId?: string;
  totalCostUsd?: number;
  ccEffort?: string;
  ccThinking?: boolean | null;
  ccPermMode?: string | null;
  composer?: ChatComposerDraft;
  /** First agentic platform used in this chat — locks the model picker (044). */
  pinnedProviderId?: ProviderId;
  /** Active preset shaping this session (built-in or custom) — not a
   *  subagent, no isolated context. See src/presets/. */
  presetId?: string;
  /** Title was generated by the cheap LLM auto-title call (chatAutoTitle.ts).
   *  Like `titleLocked`, it stops the first-line heuristic from clobbering it
   *  on the next persist; a hand rename (titleLocked) still wins. */
  autoTitled?: boolean;
}

const LEGACY_SESSION_KEY = (wsId: string, sessionId: string) =>
  `lcp.ollama.history.${wsId}.s.${sessionId}`;

export { hydrateChatStore, ensureSessionLoaded } from "./chatStoreCache";

export function loadSession(
  wsId: string,
  sessionId: string,
): ChatSession | undefined {
  return getCachedSession(wsId, sessionId);
}

export function loadSessions(wsId: string): ChatSession[] {
  return getCachedSessions(wsId);
}

export function listSessionIds(wsId: string): string[] {
  return getCachedSessionIds(wsId);
}

/** Atomic per-session write — disk-backed, no localStorage quota. */
export function saveSession(wsId: string, session: ChatSession): boolean {
  putCachedSession(wsId, session);
  void flushSessionToDisk(wsId, session);
  return true;
}

/** Merge fields without clobbering messages when absent from the patch.
 *  Never invents a new empty transcript row (composer unmount used to). */
export function patchSession(
  wsId: string,
  sessionId: string,
  patch: Partial<Omit<ChatSession, "id">>,
): boolean {
  const existing = loadSession(wsId, sessionId);
  if (!existing) {
    if (!patch.messages || patch.messages.length === 0) return false;
    return saveSession(wsId, {
      id: sessionId,
      title: patch.title ?? "Untitled",
      messages: patch.messages,
      updatedAt: Date.now(),
      ...patch,
    });
  }
  const messages = patch.messages ?? existing.messages;
  return saveSession(wsId, {
    ...existing,
    ...patch,
    id: sessionId,
    messages:
      messages.length >= existing.messages.length
        ? messages
        : existing.messages,
    updatedAt: Date.now(),
  });
}

export function deleteSession(wsId: string, id: string): void {
  removeCachedSession(wsId, id);
  remove(LEGACY_SESSION_KEY(wsId, id));
  void deleteSessionOnDisk(wsId, id);
}

export function newSessionId(): string {
  return "c_" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

export function deriveTitle(messages: ChatMessage[]): string {
  const first = messages.find((m) => m.role === "user")?.content ?? "";
  const trimmed = first.trim().split("\n")[0] ?? "";
  return trimmed.length > 60 ? trimmed.slice(0, 57) + "…" : trimmed || "Untitled";
}

/** Title to persist for a session. A hand-set (`titleLocked`) or LLM
 *  (`autoTitled`) title is authoritative — keep it, so the first-line
 *  heuristic never clobbers a good name on the next flush. Otherwise derive
 *  from the messages as before. */
export function preferredTitle(
  desc: { title?: string; titleLocked?: boolean; autoTitled?: boolean } | undefined,
  messages: ChatMessage[],
): string {
  if (desc && (desc.titleLocked || desc.autoTitled) && desc.title) {
    return desc.title;
  }
  return deriveTitle(messages);
}

/** Boot-time migration helper when disk hydrate races first save. */
export function saveSessionLegacyFallback(
  wsId: string,
  session: ChatSession,
): boolean {
  return legacySaveToLocalStorage(wsId, session);
}
