// Generate the .md operational document for the Whiteboard tab. Pure
// function: takes the discovered agents + skills and returns a markdown
// string with a "Workflow" section per agent. Used both by the live
// MarkdownPreview and by the "Save to .codetta/whiteboard.md" action.
//
// The generated document is structured like a runbook so it's useful as
// a real "how do I work with this org?" reference, not just a dump.

import type { SkillDef } from "./skills";
import type { SubagentDef } from "./subagents";

interface WhiteboardInput {
  workspaceName: string;
  agents: SubagentDef[];
  skills: SkillDef[];
}

function skillByName(
  skills: SkillDef[],
): (name: string) => SkillDef | undefined {
  const map = new Map(skills.map((s) => [s.name, s]));
  return (n) => map.get(n);
}

/**
 * Render the markdown body. Group agents by source (project/user) so
 * the document maps cleanly to the on-disk layout. Unassigned skills
 * appear as a final section.
 */
export function renderWhiteboardMd({
  workspaceName,
  agents,
  skills,
}: WhiteboardInput): string {
  const now = new Date().toISOString().slice(0, 10);
  const lookUp = skillByName(skills);
  const projectAgents = agents.filter((a) => a.source === "project");
  const userAgents = agents.filter((a) => a.source === "user");
  const usedSkillSlugs = new Set<string>();
  for (const a of agents) for (const s of a.skills) usedSkillSlugs.add(s);
  const freeSkills = skills.filter((s) => !usedSkillSlugs.has(s.name));

  const out: string[] = [];
  out.push(`# Whiteboard — ${workspaceName}`);
  out.push("");
  out.push(
    `> Generated by Quack on ${now}. Jack is the project manager (always available via Claude Code).`,
  );
  out.push(
    "> Edit the `.claude/agents/*.md` files and the `skills:` frontmatter lists to keep this in sync.",
  );
  out.push("");
  out.push(`- **${agents.length}** subagent${agents.length === 1 ? "" : "s"} (${projectAgents.length} project, ${userAgents.length} global)`);
  out.push(
    `- **${skills.length}** skill${skills.length === 1 ? "" : "s"} available`,
  );
  out.push("");

  const writeAgentGroup = (heading: string, group: SubagentDef[]) => {
    if (group.length === 0) return;
    out.push(`## ${heading}`);
    out.push("");
    for (const a of group) {
      out.push(`### ${a.name}  (${a.source})`);
      out.push("");
      if (a.description) {
        out.push(`**Description**: ${a.description}`);
        out.push("");
      }
      out.push(`**Source**: \`${a.path ?? "<unknown path>"}\``);
      out.push("");
      if (a.skills.length > 0) {
        out.push(`**Skills linked**:`);
        out.push("");
        for (const slug of a.skills) {
          const sk = lookUp(slug);
          if (sk) {
            out.push(`- \`/skills/${slug}\` — ${sk.description || "no description"}`);
          } else {
            out.push(`- \`/skills/${slug}\` — _skill not found in this workspace_`);
          }
        }
        out.push("");
      } else {
        out.push(`**Skills linked**: _(none — drag skills onto this agent in the Whiteboard tab)_`);
        out.push("");
      }
      out.push(`**Workflow**:`);
      out.push("");
      if (a.skills.length === 0) {
        out.push(
          "1. Mention `@" +
            a.name +
            "` in a Quack chat to delegate this turn to the agent.",
        );
        out.push(
          "2. Follow the agent's `description` for output format and constraints.",
        );
      } else {
        out.push(
          "1. Mention `@" +
            a.name +
            "` in a Quack chat to delegate this turn to the agent.",
        );
        out.push("2. Inside the delegated run, the agent will:");
        a.skills.forEach((slug, i) => {
          out.push(
            `   ${i + 1}. invoke \`/skills/${slug}\` — ${lookUp(slug)?.description || "no description"}`,
          );
        });
        out.push("3. Return a concise final report to the parent session.");
      }
      out.push("");
    }
  };

  writeAgentGroup("Project subagents", projectAgents);
  writeAgentGroup("Global subagents", userAgents);

  if (freeSkills.length > 0) {
    out.push("## Unassigned skills");
    out.push(
      "_Available skills not yet linked to any agent. Drag them onto an agent in the Whiteboard tab to link._",
    );
    out.push("");
    for (const s of freeSkills) {
      out.push(`- \`/skills/${s.name}\` — ${s.description || "no description"}`);
    }
    out.push("");
  }

  out.push("---");
  out.push(
    "_Regenerate this file from the Whiteboard tab → Workflows → Save to .codetta/whiteboard.md_",
  );
  out.push("");
  return out.join("\n");
}
